
import "./globals.css";
import "./data-tables-css.css";
import "./satoshi.css";
import NextAuthProvider from "@/components/NextAuthProvider";
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
const inter = Montserrat({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}




export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  return (
    <html lang="en">
      <body className={inter.className}>
      <NextAuthProvider>
       {children}
      </NextAuthProvider>
      </body>
    </html>
  );
}
