
import "./globals.css";
import "./data-tables-css.css";
import "./satoshi.css";
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import ReduxProdiver from "./providers/ReduxProvider";
import NextAuthProvider from "./providers/NextAuthProvider";
// const inter = Montserrat({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}




export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  return (
    <html lang="en">
      <body>
      <NextAuthProvider>
       <ReduxProdiver>
        {children}
       </ReduxProdiver>
      </NextAuthProvider>
      </body>
    </html>
  );
}
