export const customMessage ={
    after: 'Ce champ doit être postérieur à',
    alpha_num: 'Ce champ doit être alphanumérique',
    before: 'Ce champ doit être antérieur à',
    between: 'Ce champ doit être entre',
    confirmed: 'Ce champ doit être identique',
    date_between: 'Ce champ doit être entre les dates spécifiées',
    date_format: 'Ce champ doit suivre le format de date spécifié',
    decimal: 'Ce champ doit être un nombre décimal',
    digits: 'Ce champ doit comporter exactement les chiffres spécifiés',
    email: 'Veuillez entrer une adresse email valide',
    ext: 'Extension de fichier non valide pour ce champ',
    image: 'Seuls les fichiers image sont autorisés pour ce champ',
    included: 'Ce champ doit être une des valeurs autorisées',
    integer: 'Ce champ doit être un nombre entier',
    length: 'La longueur de ce champ doit être',
    max_value: 'Ce champ ne doit pas dépasser la valeur maximale spécifiée',
    min_value: 'Ce champ doit être au moins égal à la valeur minimale spécifiée',
    excluded: 'Ce champ ne doit pas être une des valeurs exclues',
    numeric: 'Ce champ doit être une valeur numérique',
    required: 'Ce champ est requis',
    url: 'Veuillez entrer une URL valide',
    available_quantity: 'Cette quantité est supérieure à la quantité disponible.',
    phoneOrEmail: 'Email ou numero de telephone non valide',
}